---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: kafkaansiblemoleculenode1
    box: ${MOLECULE_VAGRANT_BOX:-ubuntu/jammy64}
    cpu: 0.5
    memory: 2048
    interfaces:
      - network_name: private_network
        ip: 192.168.124.2
  - name: kafkaansiblemoleculenode2
    box: ${MOLECULE_VAGRANT_BOX:-ubuntu/jammy64}
    cpu: 0.5
    memory: 2048
    interfaces:
      - network_name: private_network
        ip: 192.168.124.3
  - name: kafkaansiblemoleculenode3
    box: ${MOLECULE_VAGRANT_BOX:-ubuntu/jammy64}
    cpu: 0.5
    memory: 2048
    interfaces:
      - network_name: private_network
        ip: 192.168.124.4
  - name: kafkaansiblemoleculenode4
    box: ${MOLECULE_VAGRANT_BOX:-ubuntu/jammy64}
    cpu: 0.5
    memory: 2048
    interfaces:
      - network_name: private_network
        ip: 192.168.124.5
  - name: kafkaansiblemoleculenode5
    box: ${MOLECULE_VAGRANT_BOX:-ubuntu/jammy64}
    cpu: 0.5
    memory: 2048
    interfaces:
      - network_name: private_network
        ip: 192.168.124.6
  - name: kafkaansiblemoleculenode6
    box: ${MOLECULE_VAGRANT_BOX:-ubuntu/jammy64}
    cpu: 0.5
    memory: 2048
    interfaces:
      - network_name: private_network
        ip: 192.168.124.7
provisioner:
  name: ansible
  # options:
  #   D: true
  #   C: true
  inventory:
    host_vars:
      kafkaansiblemoleculenode1:
        # kafka_node_roles:
        #   - controller
        kafka_node_id: 1
        kafka_node_ip: 192.168.124.2
      kafkaansiblemoleculenode2:
        # kafka_node_roles:
        #   - controller
        kafka_node_id: 2
        kafka_node_ip: 192.168.124.3
      kafkaansiblemoleculenode3:
        # kafka_node_roles:
        #   - controller
        kafka_node_id: 3
        kafka_node_ip: 192.168.124.4
      kafkaansiblemoleculenode4:
        kafka_node_id: 4
        kafka_node_ip: 192.168.124.5
        kafka_node_roles:
          - broker
      kafkaansiblemoleculenode5:
        kafka_node_id: 5
        kafka_node_ip: 192.168.124.6
        kafka_node_roles:
          - broker
      kafkaansiblemoleculenode6:
        kafka_node_id: 6
        kafka_node_ip: 192.168.124.7
        kafka_node_roles:
          - broker
verifier:
  name: ansible
