---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: kafkaansiblemoleculenode
    box: ${MOLECULE_VAGRANT_BOX:-ubuntu/jammy64}
    cpu: 1
    memory: 2048
provisioner:
  name: ansible
  inventory:
    host_vars:
      kafkaansiblemoleculenode:
        kafka_node_id: 1
        kafka_install_dependencies: true
verifier:
  name: ansible
