---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: kafkaansiblemoleculenode1
    box: ${MOLECULE_VAGRANT_BOX:-ubuntu/jammy64}
    cpu: 0.5
    memory: 2048
    interfaces:
      - network_name: private_network
        ip: 192.168.123.2
  - name: kafkaansiblemoleculenode2
    box: ${MOLECULE_VAGRANT_BOX:-ubuntu/jammy64}
    cpu: 0.5
    memory: 2048
    interfaces:
      - network_name: private_network
        ip: 192.168.123.3
  - name: kafkaansiblemoleculenode3
    box: ${MOLECULE_VAGRANT_BOX:-ubuntu/jammy64}
    cpu: 0.5
    memory: 2048
    interfaces:
      - network_name: private_network
        ip: 192.168.123.4
provisioner:
  name: ansible
  inventory:
    host_vars:
      kafkaansiblemoleculenode1:
        kafka_node_id: 1
        kafka_node_ip: 192.168.123.2
      kafkaansiblemoleculenode2:
        kafka_node_id: 2
        kafka_node_ip: 192.168.123.3
      kafkaansiblemoleculenode3:
        kafka_node_id: 3
        kafka_node_ip: 192.168.123.4
verifier:
  name: ansible
